spring:
  application:
    name: tech-test
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 2GB
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

client:
  country:
    blacklist:
      - CN
      - ES
      - US
  isp:
    blacklist:
      - AWS
      - GCP
      - Azure

csv:
  validation:
    enabled: true

files:
  upload:
    save-file: true
    directory: files/upload
  download:
    directory: files/download